### ISSUE TITLE
Segmentation fault on Mac

### ISSUE THREAD

**Issue by kibaekkim** [SCIP-Interfaces/CSIP#16]
``` bash
Running tests...
  test_lp
  test_mip
  test_mip2
  test_mip3
  test_socp
make: *** [test] Segmentation fault: 1
```

**Comment by leethargo** [comment]
The tests work on my machines and I don't have access to a Mac.

I assume that the tests were run when linking agains a `libscipopt` compiled in `OPT=opt` mode. Does it still segfault in `OPT=dbg`? Could you maybe provide a stacktrace? Was IPOPT compiled with SCIP?

**Comment by fserra** [comment]
@kibaekkim can you provide more info?
