### ISSUE TITLE
upgrade to scip 4.0

### ISSUE THREAD

**Issue by fserra** [SCIP-Interfaces/CSIP#29]
@leethargo  I guess I'll need some help here regarding the versioning of CSIP.  
Should we go to CSIP 0.3.7 or CSIP 0.4.0 ?

The interface of CSIP didn't change

**Comment by leethargo** [comment]
What does it mean to support the new SCIP, can't we support both?

Does any of the code of CSIP change because of that? If so, then we require the user to install the new SCIP, which I feel is a breaking change, so we should go to 0.4.0.

**Comment by fserra** [comment]
Well, there is a single line of code changed in CSIP.

I guess we could support both, but why?

**Comment by leethargo** [comment]
Then the update is not a breaking change, and people who update SCIP.jl with Julia's package manager don't end up with a broken system.

On the other hand, users would not even know about the new SCIP...

**Comment by fserra** [comment]
it is not a breaking change, but it will just not compile with SCIP 3.2.1, or am I missing your point?

**Comment by leethargo** [comment]
Yes, so an update of SCIP.jl will tell them that CSIP is out-of-date, but if the user then deletes CSIP (as instructed) and runs `Pkg.build("SCIP")` it will fail.

**Comment by fserra** [comment]
why will it fail? scip 4 is out now ;)

**Comment by leethargo** [comment]
Users still have to download and install it, nothing is automated.

**Comment by fserra** [comment]
yeah, but that has always been then case, right?

**Comment by mlubin** [comment]
Given that everything is already manual, it's okay with me if an update to SCIP.jl results in a broken system. However, it would be nice to provide a useful error message, e.g., as we do with [ECOS](https://github.com/JuliaOpt/ECOS.jl/blob/baf66b3d6cb7aa9c2a4f293fb27726b6139dac21/src/ECOS.jl#L42). Whoever wants to keep using the old version of SCIP can pin SCIP.jl.

**Comment by leethargo** [comment]
Well, we have that [error message](https://github.com/SCIP-Interfaces/SCIP.jl/blob/master/src/SCIP.jl#L30) in SCIP.jl, but refering to CSIP, not SCIP.

@fserra: Didn't you already have a pull request with a one-line change? We should then also update the README and be explicit about SCIP's version.

**Comment by fserra** [comment]
yeah sure. So what is it then? 0.4.0 or 0.3.7??

**Comment by leethargo** [comment]
Go for 0.4.0.
