### ISSUE TITLE
Build scipoptlib failed

### ISSUE THREAD

**Issue by waldstein1983** [SCIP-Interfaces/CSIP#33]
Hi all,
I come up with an error when building SCIP with "make SHARED=true GMP=false READLINE=false ZLIB=false scipoptlib" before building CSIP, as:
9801a7b319bb:scip-4.0.0 baohuaw$ make SHARED=true GMP=false READLINE=false ZLIB=false scipoptlib
make/make.project:477: ZIMPL was deactived because of missing GMP support.
make: *** No rule to make target `scipoptlib'.  Stop.
Can you please support me?
Thx

**Comment by leethargo** [comment]
The `make scipoptlib` command is not supposed to be executed from the `scip` directory, but "one level up". Please download the [scipoptsuite-4.0.0.tgz](http://scip.zib.de/download.php?fname=scipoptsuite-4.0.0.tgz) and run `make` from the top-level dir.

**Comment by waldstein1983** [comment]
Thanks. I see.
Plus, I use a scipsolver.so, which is built before by using "make SHARED=true" in scip-4.0.0 folder. It also works :-)
Another question is, why must "GMP=false READLINE=false" in your make script?
Are not that 2 libs require by SCIP?

**Comment by fserra** [comment]
because those requires libraries that are not available in every system.
also, they enable features that are not possible to use via the julia
interface

**Comment by waldstein1983** [comment]
I see. Thanks.

2017-05-23 11:21 GMT+08:00 fserra <notifications@github.com>:

> because those requires libraries that are not available in every system.
> also, they enable features that are not possible to use via the julia
> interface
>
