### ISSUE TITLE
Install instruccions not working

### ISSUE THREAD

**Issue by iaravena** [SCIP-Interfaces/CSIP#39]
I just tried to install 0.5.0, but the installation instructions are not working. They break because make is pointed to the installation folder instead of the source folder when looking for SCIP headers, i.e. at

`if [ -e $(SCIPOPTDIR)/include/scip/scip.h ] ; \`

while scip.h is in

`/path/to/source/scipoptsuite-5.0.0/scip/src/scip/scip.h`

I didn't wanted to submit a pull request because I don't know the best way to proceed here. Should there be two environment variables one pointing to the build directory and another pointing to the source directory? is there maybe a better approach?

**Comment by leethargo** [comment]
The link should point to the *installation directory*, and not the build dir nor the path of the extracted sources.

Did you use `cmake` for the build?
Did you configure `CMAKE_INSTALL_PREFIX`?
Did you use  run `make install` also?
