### ISSUE TITLE
add user cut callbacks

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/CSIP#4]
Separated from #3

**Comment by fserra** [comment]
@mlubin, wanna write some tests for this? :)

**Comment by mlubin** [comment]
User cuts are very hard to test since by definition they should not affect the optimal solution...
JuMP's tests are here: https://github.com/JuliaOpt/JuMP.jl/blob/93b870e3d7b3eb6c8995993921a8d3466453f9e3/test/callback.jl#L109

**Comment by fserra** [comment]
Maybe the [admipex4](http://perso.ensta-paristech.fr/~diam/ro/online/cplex/examples/cplex/src/c/admipex4.c) of cplex is a good test?

**Comment by mlubin** [comment]
The license there is sketchy, not sure we can include a translation of it in the repository.

**Comment by leethargo** [comment]
Closed. Should be done in SCIP.jl directly, instead.
