### ISSUE TITLE
Supporting trig expressions (SCIP_EXPR_{SIN|COS|TAN})

### ISSUE THREAD

**Issue by rdeits** [SCIP-Interfaces/CSIP#40]
I'm interested in using CSIP (from Julia with SCIP.jl) to solve nonlinear optimizations involving trig functions, but it looks like CSIP doesn't currently support those expression types. I'm willing to put in some effort to add them (I'm not familiar with CSIP, but it doesn't look too bad), but I wanted to first make sure that such a change would be welcome. Is there a reason that trig functions were excluded?

**Comment by fserra** [comment]
Hi. The reason is that SCIP itself doesn't support trigonometric functions for the time being

**Comment by rdeits** [comment]
Really? I see code to handle trig functions in, for example, `scip/src/nlpi/typ_expr.h`: 

```
   SCIP_EXPR_SIN       = 19,  /**< sinus (1 operand) */
   SCIP_EXPR_COS       = 20,  /**< cosinus (1 operand) */
   SCIP_EXPR_TAN       = 21,  /**< tangent (1 operand) */
```

and those cases appear to be handled in `exprsimplifyFlattenPolynomials` in `expr.c`. Is the support in SCIP incomplete or disabled somehow?

**Comment by fserra** [comment]
it is incomplete and produces an error. in cons_nonlinear there is something like

```c
         case SCIP_EXPR_SIN:
         case SCIP_EXPR_COS:
         case SCIP_EXPR_TAN:
         case SCIP_EXPR_SIGN:
            /* case SCIP_EXPR_ERF   : */
            /* case SCIP_EXPR_ERFI  : */
         {
            SCIPerrorMessage("no support for trigonometric or sign operands yet\n");
            return SCIP_ERROR;
         }
```

**Comment by rdeits** [comment]
Got it, thanks!
