### ISSUE TITLE
Support for adding nonlinear constraints from lazy callbacks

### ISSUE THREAD

**Issue by leethargo** [SCIP-Interfaces/CSIP#9]
At the moment, only adding linear constraints is implemented, which is what all the solvers can do.

We should also support adding quadratic and SOS1/SOS2 constraints, because it's easy.

**Comment by fserra** [comment]
@mlubin does JuMP allow adding quadratic, sos1, sos2 and nonlinear constraints from callbacks??

**Comment by mlubin** [comment]
This is not supported in MathProgBase, but I can think of instances where I would want to play with this feature.

**Comment by mlubin** [comment]
If it's accessible in CSIP and SCIP.jl it's possible to make SCIP-specific hacks to JuMP to use the feature.

**Comment by leethargo** [comment]
Closed. Should be done in SCIP.jl directly, instead.
